### ISSUE TITLE
Error when generating the manifest for AVSR

### ISSUE THREAD

**Issue by joyolee** [facebookresearch/muavic#9]
Dear authors,

  Thanks a lot for your work. When generating manifests for AVSR, I meet the following error, which can not restart from the breaking point:

> Creating fr/train manifest:  26%|██▌       | 30189/116045 [10:24:50<40:25:00,  1.69s/it]
> Creating fr/train manifest:  26%|██▌       | 30195/116045 [10:24:53<25:27:27,  1.07s/it]
> Creating fr/train manifest:  26%|██▌       | 30197/116045 [10:24:58<33:41:41,  1.41s/it]
> Creating fr/train manifest:  26%|██▌       | 30199/116045 [10:25:00<30:51:53,  1.29s/it]Exception in thread QueueManagerThread:
> Traceback (most recent call last):
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> 
> Creating fr/train manifest:  26%|██▌       | 30202/116045 [10:25:03<29:36:35,  1.24s/it]
>     self.run()
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/process.py", line 394, in _queue_management_worker
>     work_item.future.set_exception(bpe)
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/_base.py", line 547, in set_exception
>     raise InvalidStateError('{}: {!r}'.format(self._state, self))
> concurrent.futures._base.InvalidStateError: CANCELLED: <Future at 0x7fc3fa091ca0 state=cancelled>
> concurrent.futures.process._RemoteTraceback: 
> '''
> Traceback (most recent call last):
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/process.py", line 368, in _queue_management_worker
>     result_item = result_reader.recv()
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/multiprocessing/connection.py", line 251, in recv
>     return _ForkingPickler.loads(buf.getbuffer())
> TypeError: __init__() missing 2 required positional arguments: 'stdout' and 'stderr'
> '''
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "get_data.py", line 115, in <module>
>     main(args)
>   File "get_data.py", line 84, in main
>     prepare_mtedx(args)
>   File "get_data.py", line 31, in prepare_mtedx
>     prepare_mtedx_avsr_manifests(args["mtedx"], args["src_lang"], args["muavic"])
>   File "/beegfs/work/zhengyangli/muavic/mtedx_utils.py", line 268, in prepare_mtedx_avsr_manifests
>     process_map(
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 105, in process_map
>     return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
>     return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
>     for obj in iterable:
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
>     for element in iterable:
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
>     yield fs.pop().result()
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/_base.py", line 444, in result
>     return self.__get_result()
>   File "/home/zhengyangli/anaconda3/envs/muavic/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> slurmstepd: error: *** JOB 536548 ON gpu01 CANCELLED AT 2023-04-21T10:16:11 ***

Do you have any clue to solve the problem?

Best regards,
Zhengyang

**Comment by Anwarvic** [comment]
Hi @joyolee ,

Thanks for raising this issue!

This issue occurs when `ffmpeg.prob` is not able to read the video info. This was fixed in our latest commit [db0f71e](https://github.com/facebookresearch/muavic/commit/db0f71e7f2b6dbd8b158ee43ebc108b40df3be87).

Please, run `git pull` to fetch our latest updates and re-run your script!

**Comment by Anwarvic** [comment]
Hi @joyolee,

Is the matter at hand resolved, or are you still encountering difficulties? If it is the latter, please don't hesitate to offer additional information.

**Comment by joyolee** [comment]
Hi, yes. It is solved. I am going to close the issue. Thank you very much 😃 

> Hi @joyolee,
> 
> 
> 
> Is the matter at hand resolved, or are you still encountering difficulties? If it is the latter, please don't hesitate to offer additional information.
